### ISSUE TITLE
DB file is keeping size after poll

### ISSUE THREAD

**Issue by amacierzynski** [sysgears/java-berkleydb-queue#1]
Hey,

Just wanted to ask if this is an issue or functionality?
I am doing 10k pushes, than want to make 10k polls. Files which is created is not losing any weight actually.

Can you provide me more info how it is working, and if it is possible to remove file after sucessfull polling?

Thanks,
Adam

**Comment by larixer** [comment]
@amacierzynski You should check Oracle Berkley DB Java Edition architecture and how it general works from its documentation and articles. Relevant quote from one of the articles:

> When JE creates an environment, it simply creates a couple of files: a log file 00000000.jdb and a lock file je.lck. It is not obvious what JE databases are available in an environment by looking into the environment home directory. JE appends all persistent activities such as transactions, insertions, updates and deletions to the log file. When 00000000.jdb is full (the default size is 10MB), 00000001.jdb is created, etc., up to ffffffff.jdb. If an environment is opened as read-write, a log cleaning thread is started that monitors log files utilization. When most of the records in a particular log file have been obsoleted by updates or deletions in later log files, the log cleaning thread copies the remaining records to the end of the latest log file and deletes the old log file. The cleaner chooses which log file to operate based on the current space utilization within the log file.

But you should really delve into documentation details to fully understand and control how log is written and cleaned up. It cannot be explained in couple of sentences and is out of scope to explain it here,
